// Generated by CodeLedger. Do not edit — it is overwritten on every sync.
// Recomputes badges/ from index.json so a streak that ends on a day with
// no commits still shows the truth. Run by .github/workflows/codeledger-badges.yml.

// dev/refresh-badges-entry.js
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname } from "node:path";

// src/core/gamification.js
var POINTS = Object.freeze({
  Easy: 10,
  Medium: 25,
  Hard: 50,
  Unknown: 10
});
var RECALL_MULTIPLIER = 0.4;
var RECALL_COOLDOWN_DAYS = 3;
var DEFAULT_CONFIG = Object.freeze({
  /** Master switch. When false every gamification surface is hidden. */
  enabled: true,
  /** Points needed to close a day. 25 = one Medium, or two Easies plus change. */
  dailyTargetPoints: 25,
  /** Reaching this multiple of the target in one day earns a streak freeze. */
  freezeEarnMultiplier: 2,
  /** Freezes you can bank. Uncapped banking removes all pressure. */
  maxFreezes: 5,
  /** Points needed the next day to buy back a missed day, as a multiple. */
  penaltyMultiplier: 1.5,
  /** Days after a vacation that run at a reduced target while you warm up. */
  iceBreakerDays: 3,
  /** Target multiplier during the ice-breaker ramp. */
  iceBreakerMultiplier: 0.5,
  /** Minutes to add to UTC to get the user's local day boundary. */
  utcOffsetMinutes: -(/* @__PURE__ */ new Date()).getTimezoneOffset()
});
var CONFIG_KEYS = Object.freeze(
  Object.keys(DEFAULT_CONFIG).filter((k) => k !== "enabled")
);
var LEVELS = Object.freeze([
  { level: 1, name: "Initiate", at: 0 },
  { level: 2, name: "Apprentice", at: 100 },
  { level: 3, name: "Practitioner", at: 300 },
  { level: 4, name: "Analyst", at: 700 },
  { level: 5, name: "Engineer", at: 1500 },
  { level: 6, name: "Architect", at: 3e3 },
  { level: 7, name: "Strategist", at: 6e3 },
  { level: 8, name: "Veteran", at: 1e4 },
  { level: 9, name: "Master", at: 18e3 },
  { level: 10, name: "Grandmaster", at: 3e4 }
]);
var MS_PER_DAY = 864e5;
function dayKey(ts, utcOffsetMinutes = DEFAULT_CONFIG.utcOffsetMinutes) {
  const ms = ts instanceof Date ? ts.getTime() : typeof ts === "string" ? Date.parse(ts) : ts;
  if (!Number.isFinite(ms)) return "";
  return new Date(ms + utcOffsetMinutes * 6e4).toISOString().slice(0, 10);
}
function keyToMs(key) {
  return Date.parse(`${key}T00:00:00.000Z`);
}
function addDays(key, n) {
  return new Date(keyToMs(key) + n * MS_PER_DAY).toISOString().slice(0, 10);
}
function daysBetween(a, b) {
  return Math.round((keyToMs(b) - keyToMs(a)) / MS_PER_DAY);
}
function pointsFor(difficulty, opts = {}) {
  const base = POINTS[difficulty] ?? POINTS.Unknown;
  return opts.recall ? Math.round(base * RECALL_MULTIPLIER) : base;
}
function usableStamp(v) {
  const n = Number(v);
  return Number.isFinite(n) && n > 0;
}
function scoreEvents(problems, config = DEFAULT_CONFIG) {
  const cfg = { ...DEFAULT_CONFIG, ...config };
  const events = [];
  for (const p of problems || []) {
    if (!p) continue;
    const id = p.canonicalId || `${p.platform || "?"}:${p.titleSlug || p.title || "?"}`;
    const difficulty = p.difficulty || "Unknown";
    const title = p.title || p.titleSlug || id;
    const stamps = [];
    if (usableStamp(p.timestamp)) stamps.push(Number(p.timestamp));
    for (const h of p.solveHistory || []) {
      const t = h?.timestamp ?? h;
      if (usableStamp(t)) stamps.push(Number(t));
    }
    if (!stamps.length) {
      if (p._solveDateUnknown) {
        events.push({
          day: null,
          points: pointsFor(difficulty, { recall: false }),
          difficulty,
          recall: false,
          dateUnknown: true,
          id,
          title
        });
      }
      continue;
    }
    stamps.sort((a, b) => a - b);
    let lastScored = -Infinity;
    stamps.forEach((ts, i) => {
      const recall = i > 0;
      if (recall && ts - lastScored < RECALL_COOLDOWN_DAYS * MS_PER_DAY) return;
      lastScored = ts;
      events.push({
        day: dayKey(ts, cfg.utcOffsetMinutes),
        points: pointsFor(difficulty, { recall }),
        difficulty,
        recall,
        id,
        title
      });
    });
  }
  events.sort((a, b) => {
    const x = a.day || "";
    const y = b.day || "";
    return x < y ? -1 : x > y ? 1 : 0;
  });
  return events;
}
function buildDailyPoints(problems, config = DEFAULT_CONFIG) {
  const days = /* @__PURE__ */ new Map();
  for (const e of scoreEvents(problems, config)) {
    if (!e.day) continue;
    let d = days.get(e.day);
    if (!d) {
      d = { points: 0, solves: 0, recalls: 0, byDifficulty: {} };
      days.set(e.day, d);
    }
    d.points += e.points;
    if (e.recall) d.recalls += 1;
    else d.solves += 1;
    d.byDifficulty[e.difficulty] = (d.byDifficulty[e.difficulty] || 0) + 1;
  }
  return days;
}
function isVacationDay(key, vacations) {
  for (const v of vacations || []) {
    if (!v?.start) continue;
    if (key < v.start) continue;
    if (v.end && key > v.end) continue;
    return true;
  }
  return false;
}
function computeStreak(days, config, vacations, todayKey, floorDay) {
  const cfg = { ...DEFAULT_CONFIG, ...config };
  const target = Math.max(1, Math.round(cfg.dailyTargetPoints));
  const freezeAt = target * Math.max(1, cfg.freezeEarnMultiplier);
  const penaltyCost = Math.ceil(Math.max(1, cfg.penaltyMultiplier) * target);
  const keys = [...days.keys()].sort();
  if (!keys.length) {
    return {
      current: 0,
      longest: 0,
      freezes: 0,
      freezesSpent: 0,
      frozenDays: [],
      penaltyDays: [],
      brokenAt: null,
      timeline: []
    };
  }
  const first = floorDay && floorDay > keys[0] ? floorDay : keys[0];
  const last = todayKey > first ? todayKey : first;
  let current = 0;
  let longest = 0;
  let freezes = 0;
  let freezesSpent = 0;
  const frozenDays = [];
  const penaltyDays = [];
  const timeline = [];
  let brokenAt = null;
  for (let key = first; key <= last; key = addDays(key, 1)) {
    const bucket = days.get(key);
    const points = bucket?.points || 0;
    const vacation = isVacationDay(key, vacations);
    let status;
    if (vacation) {
      status = "vacation";
    } else if (points >= target) {
      current += 1;
      status = "complete";
      if (points >= freezeAt && freezes < cfg.maxFreezes) {
        freezes += 1;
        status = "earned-freeze";
      }
    } else if (key === todayKey) {
      status = points > 0 ? "partial" : "pending";
    } else {
      const nextPoints = days.get(addDays(key, 1))?.points || 0;
      if (nextPoints >= penaltyCost) {
        current += 1;
        status = "restored";
        penaltyDays.push(key);
      } else if (freezes > 0) {
        freezes -= 1;
        freezesSpent += 1;
        current += 1;
        status = "frozen";
        frozenDays.push(key);
      } else {
        longest = Math.max(longest, current);
        current = 0;
        brokenAt = key;
        status = "missed";
      }
    }
    timeline.push({ day: key, points, status, vacation });
  }
  longest = Math.max(longest, current);
  return {
    current,
    longest,
    freezes,
    freezesSpent,
    frozenDays,
    penaltyDays,
    brokenAt,
    timeline
  };
}
function levelFor(points) {
  const p = Math.max(0, Number(points) || 0);
  let idx = 0;
  for (let i = 0; i < LEVELS.length; i++) if (p >= LEVELS[i].at) idx = i;
  const cur = LEVELS[idx];
  const next = LEVELS[idx + 1] || null;
  const into = p - cur.at;
  const span = next ? next.at - cur.at : 0;
  return {
    ...cur,
    next,
    into,
    span,
    progress: next ? Math.min(1, into / span) : 1
  };
}
var ACHIEVEMENTS = Object.freeze([
  {
    id: "first-blood",
    emoji: "\u{1FA78}",
    name: "First Blood",
    hint: "Commit your first solve",
    test: (s) => s.totalSolves >= 1
  },
  {
    id: "ten-down",
    emoji: "\u{1F51F}",
    name: "Ten Down",
    hint: "Solve 10 problems",
    test: (s) => s.totalSolves >= 10
  },
  {
    id: "century",
    emoji: "\u{1F4AF}",
    name: "Century",
    hint: "Solve 100 problems",
    test: (s) => s.totalSolves >= 100
  },
  {
    id: "half-k",
    emoji: "\u{1F3DB}\uFE0F",
    name: "Five Hundred",
    hint: "Solve 500 problems",
    test: (s) => s.totalSolves >= 500
  },
  {
    id: "week-streak",
    emoji: "\u{1F525}",
    name: "Week On Fire",
    hint: "7-day streak",
    test: (s) => s.longestStreak >= 7
  },
  {
    id: "month-streak",
    emoji: "\u{1F30B}",
    name: "Month On Fire",
    hint: "30-day streak",
    test: (s) => s.longestStreak >= 30
  },
  {
    id: "hundred-streak",
    emoji: "\u2604\uFE0F",
    name: "Unbroken",
    hint: "100-day streak",
    test: (s) => s.longestStreak >= 100
  },
  {
    id: "hard-mode",
    emoji: "\u{1F480}",
    name: "Hard Mode",
    hint: "Solve 25 Hard problems",
    test: (s) => (s.byDifficulty.Hard || 0) >= 25
  },
  {
    id: "polyglot",
    emoji: "\u{1F5E3}\uFE0F",
    name: "Polyglot",
    hint: "Solve in 5 languages",
    test: (s) => s.languageCount >= 5
  },
  {
    id: "explorer",
    emoji: "\u{1F9ED}",
    name: "Explorer",
    hint: "Solve on 3 platforms",
    test: (s) => s.platformCount >= 3
  },
  {
    id: "well-rounded",
    emoji: "\u{1F3AF}",
    name: "Well Rounded",
    hint: "Cover 15 topics",
    test: (s) => s.topicCount >= 15
  },
  {
    id: "rememberer",
    emoji: "\u{1F9E0}",
    name: "Rememberer",
    hint: "50 recall solves",
    test: (s) => s.totalRecalls >= 50
  },
  {
    id: "double-day",
    emoji: "\u26A1",
    name: "Double Day",
    hint: "Hit twice the daily target in one day",
    test: (s) => s.bestDayPoints >= s.dailyTargetPoints * 2
  },
  {
    id: "comeback",
    emoji: "\u{1FA83}",
    name: "Comeback",
    hint: "Buy back a missed day with the penalty",
    test: (s) => s.penaltyDays.length >= 1
  },
  {
    id: "level-five",
    emoji: "\u2B50",
    name: "Engineer",
    hint: "Reach level 5",
    test: (s) => s.level.level >= 5
  },
  {
    id: "level-ten",
    emoji: "\u{1F451}",
    name: "Grandmaster",
    hint: "Reach level 10",
    test: (s) => s.level.level >= 10
  },
  {
    id: "second-opinion",
    emoji: "\u{1F50D}",
    name: "Second Opinion",
    hint: "Get 10 solutions reviewed",
    needsAI: true,
    test: (s) => s.totalReviews >= 10
  },
  {
    id: "peer-reviewed",
    emoji: "\u{1F4DD}",
    name: "Peer Reviewed",
    hint: "Get 100 solutions reviewed",
    needsAI: true,
    test: (s) => s.totalReviews >= 100
  }
]);
function computeSnapshot(problems, options = {}) {
  const cfg = { ...DEFAULT_CONFIG, ...options.config || {} };
  const vacations = options.vacations || [];
  const now = Number.isFinite(options.now) ? options.now : Date.now();
  const today = dayKey(now, cfg.utcOffsetMinutes);
  const events = scoreEvents(problems, cfg);
  const days = buildDailyPoints(problems, cfg);
  const streak = computeStreak(days, cfg, vacations, today, options.streakFloorDay);
  let totalPoints = 0;
  let totalRecalls = 0;
  const byDifficulty = {};
  for (const e of events) {
    totalPoints += e.points;
    if (e.recall) totalRecalls += 1;
    else byDifficulty[e.difficulty] = (byDifficulty[e.difficulty] || 0) + 1;
  }
  const languages = /* @__PURE__ */ new Set();
  const platforms = /* @__PURE__ */ new Set();
  const topics = /* @__PURE__ */ new Set();
  let totalReviews = 0;
  for (const p of problems || []) {
    if (!p) continue;
    const lang = p.lang?.name || p.lang?.slug;
    if (lang) languages.add(String(lang).toLowerCase());
    if (p.platform) platforms.add(p.platform);
    for (const t of p.tags || []) if (t) topics.add(String(t).toLowerCase());
    if (typeof p.aiReview === "string" && p.aiReview.trim()) totalReviews += 1;
  }
  let bestDayPoints = 0;
  let bestDay = null;
  for (const [key, d] of days) {
    if (d.points > bestDayPoints) {
      bestDayPoints = d.points;
      bestDay = key;
    }
  }
  const iceBreaker = computeIceBreaker(vacations, today, cfg);
  const effectiveTarget = iceBreaker.active ? Math.max(1, Math.round(cfg.dailyTargetPoints * cfg.iceBreakerMultiplier)) : Math.max(1, Math.round(cfg.dailyTargetPoints));
  const todayBucket = days.get(today) || { points: 0, solves: 0, recalls: 0, byDifficulty: {} };
  const yesterday = addDays(today, -1);
  const yesterdayMissed = streak.timeline.find((t) => t.day === yesterday)?.status === "missed";
  const snapshot = {
    // config echoed back so renderers never need their own copy
    enabled: cfg.enabled !== false,
    dailyTargetPoints: cfg.dailyTargetPoints,
    effectiveTarget,
    // The day boundary this snapshot was computed against. It has to travel:
    // a GitHub Actions runner is on UTC, so a refresh that fell back to its own
    // offset would roll the day over at the wrong hour for everyone else.
    utcOffsetMinutes: cfg.utcOffsetMinutes,
    totalPoints,
    totalSolves: events.filter((e) => !e.recall).length,
    totalRecalls,
    totalReviews,
    byDifficulty,
    languageCount: languages.size,
    platformCount: platforms.size,
    topicCount: topics.size,
    today,
    todayPoints: todayBucket.points,
    todaySolves: todayBucket.solves,
    todayDone: todayBucket.points >= effectiveTarget,
    todayRemaining: Math.max(0, effectiveTarget - todayBucket.points),
    currentStreak: streak.current,
    longestStreak: streak.longest,
    freezes: streak.freezes,
    freezesSpent: streak.freezesSpent,
    frozenDays: streak.frozenDays,
    penaltyDays: streak.penaltyDays,
    timeline: streak.timeline,
    bestDay,
    bestDayPoints,
    activeDays: days.size,
    level: levelFor(totalPoints),
    vacationActive: isVacationDay(today, vacations),
    iceBreaker,
    /**
     * What it would cost to save the streak right now: null when nothing is at
     * risk, otherwise the points needed today and how they would be paid.
     */
    rescue: null
  };
  if (yesterdayMissed && !snapshot.vacationActive) {
    const cost = Math.ceil(cfg.penaltyMultiplier * cfg.dailyTargetPoints);
    snapshot.rescue = {
      kind: "penalty",
      requiredPoints: cost,
      remaining: Math.max(0, cost - todayBucket.points),
      restoresDay: yesterday
    };
  }
  snapshot.achievements = ACHIEVEMENTS.map((a) => ({
    id: a.id,
    emoji: a.emoji,
    name: a.name,
    hint: a.hint,
    needsAI: a.needsAI === true,
    earned: !!a.test(snapshot)
  }));
  snapshot.earnedCount = snapshot.achievements.filter((a) => a.earned).length;
  return snapshot;
}
function computeIceBreaker(vacations, today, cfg) {
  const ended = (vacations || []).filter((v) => v?.end && v.end < today).sort((a, b) => a.end < b.end ? 1 : -1)[0];
  if (!ended) return { active: false, dayOf: 0, total: cfg.iceBreakerDays, endedOn: null };
  const since = daysBetween(ended.end, today);
  const active = since >= 1 && since <= cfg.iceBreakerDays;
  return {
    active,
    dayOf: active ? since : 0,
    total: cfg.iceBreakerDays,
    endedOn: ended.end
  };
}

// src/core/badge-svg.js
var COLORS = Object.freeze({
  fire: "#f97316",
  ice: "#38bdf8",
  points: "#8b5cf6",
  level: "#22c55e",
  easy: "#22c55e",
  medium: "#f59e0b",
  hard: "#ef4444",
  slate: "#334155",
  dim: "#64748b",
  vacation: "#0ea5e9"
});
function escapeXml(s) {
  return String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}
function textWidth(text) {
  let w = 0;
  for (const ch of String(text ?? "")) {
    const code = ch.codePointAt(0);
    if (code > 126976)
      w += 12;
    else if (/[MW@%]/.test(ch)) w += 9.5;
    else if (/[A-Z]/.test(ch)) w += 7.5;
    else if (/[ijltfr.,:;'!|]/.test(ch)) w += 3.5;
    else if (/[mw]/.test(ch)) w += 9;
    else if (/[0-9]/.test(ch)) w += 6.5;
    else if (ch === " ") w += 3.5;
    else w += 6.2;
  }
  return Math.ceil(w);
}
function badge({ label, value, color = COLORS.slate, labelColor = "#555", title }) {
  const pad = 10;
  const labelW = textWidth(label) + pad * 2;
  const valueW = textWidth(value) + pad * 2;
  const total = labelW + valueW;
  const alt = escapeXml(title || `${label}: ${value}`);
  const text = (str, x, w) => `
    <text x="${x + w / 2}" y="15" fill="#010101" fill-opacity=".3" textLength="${textWidth(str)}">${escapeXml(str)}</text>
    <text x="${x + w / 2}" y="14" fill="#fff" textLength="${textWidth(str)}">${escapeXml(str)}</text>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${total}" height="20" role="img" aria-label="${alt}">
  <title>${alt}</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r"><rect width="${total}" height="20" rx="3" fill="#fff"/></clipPath>
  <g clip-path="url(#r)">
    <rect width="${labelW}" height="20" fill="${escapeXml(labelColor)}"/>
    <rect x="${labelW}" width="${valueW}" height="20" fill="${escapeXml(color)}"/>
    <rect width="${total}" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,DejaVu Sans,Geneva,sans-serif" font-size="11">${text(label, 0, labelW)}${text(value, labelW, valueW)}
  </g>
</svg>`;
}
var MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
function asOfLabel(dayKey2) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(dayKey2 || ""));
  if (!m) return "";
  const month = MONTHS[Number(m[2]) - 1];
  if (!month) return "";
  return `${month} ${Number(m[3])}`;
}
function badgeSpecs(snapshot) {
  const s = snapshot || {};
  const n = s.currentStreak || 0;
  const asOf = asOfLabel(s.today);
  const stamp = asOf ? ` \xB7 ${asOf}` : "";
  const l = s.level || { level: 1, name: "Initiate" };
  const d = s.byDifficulty || {};
  const freezes = s.freezes || 0;
  return {
    streak: s.vacationActive ? {
      label: "streak",
      value: `on vacation${stamp}`,
      color: COLORS.vacation,
      title: `On vacation${asOf ? ` as of ${asOf}` : ""} \u2014 the streak is held, not broken`
    } : {
      label: "streak",
      value: `${n === 1 ? "1 day" : `${n} days`}${stamp}`,
      color: n > 0 ? COLORS.fire : COLORS.dim,
      title: `Current solving streak: ${n} day${n === 1 ? "" : "s"}${asOf ? ` as of ${asOf}` : ""}`
    },
    points: {
      label: "points",
      value: formatCount(s.totalPoints || 0),
      color: COLORS.points
    },
    level: { label: `level ${l.level}`, value: String(l.name), color: COLORS.level },
    solved: {
      label: "solved",
      value: formatCount(s.totalSolves || 0),
      color: COLORS.slate
    },
    difficulty: {
      label: "solved",
      value: `${d.Easy || 0} easy \xB7 ${d.Medium || 0} medium \xB7 ${d.Hard || 0} hard`,
      color: COLORS.medium
    },
    freezes: {
      label: "freezes",
      value: String(freezes),
      color: freezes > 0 ? COLORS.ice : COLORS.dim,
      title: `${freezes} streak freeze${freezes === 1 ? "" : "s"} banked`
    }
  };
}
var BADGE_NAMES = Object.freeze([
  "streak",
  "points",
  "level",
  "solved",
  "difficulty",
  "freezes"
]);
function streakBadge(snapshot) {
  return badge(badgeSpecs(snapshot).streak);
}
function pointsBadge(snapshot) {
  return badge(badgeSpecs(snapshot).points);
}
function levelBadge(snapshot) {
  return badge(badgeSpecs(snapshot).level);
}
function solvedBadge(snapshot) {
  return badge(badgeSpecs(snapshot).solved);
}
function difficultyBadge(snapshot) {
  return badge(badgeSpecs(snapshot).difficulty);
}
function freezeBadge(snapshot) {
  return badge(badgeSpecs(snapshot).freezes);
}
function formatCount(n) {
  const v = Number(n) || 0;
  if (v < 1e3) return String(v);
  if (v < 1e6) return `${(v / 1e3).toFixed(v < 1e4 ? 1 : 0)}k`;
  return `${(v / 1e6).toFixed(1)}M`;
}
var CARD_THEMES = Object.freeze({
  dark: {
    bg0: "#0f172a",
    bg1: "#1e293b",
    border: "#334155",
    title: "#e2e8f0",
    muted: "#94a3b8",
    faint: "#64748b",
    stamp: "#475569",
    track: "#334155",
    streak: COLORS.fire,
    points: COLORS.points,
    solved: COLORS.level
  },
  light: {
    bg0: "#ffffff",
    bg1: "#f1f5f9",
    border: "#cbd5e1",
    title: "#0f172a",
    muted: "#475569",
    faint: "#64748b",
    stamp: "#94a3b8",
    track: "#e2e8f0",
    streak: "#c2410c",
    points: "#6d28d9",
    solved: "#15803d"
  }
});
var CARD_MOTION = `<style>
    .bar,.n{transform-box:fill-box}
    .bar{transform-origin:left center}
    @media (prefers-reduced-motion: no-preference){
      .bar{animation:cl-grow .9s cubic-bezier(.22,1,.36,1) both}
      .n{animation:cl-rise .5s ease-out both}
      .n2{animation-delay:.08s}
      .n3{animation-delay:.16s}
    }
    @keyframes cl-grow{from{transform:scaleX(0)}to{transform:scaleX(1)}}
    @keyframes cl-rise{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
  </style>`;
function streakCard(snapshot, opts = {}) {
  const t = CARD_THEMES[opts.theme === "light" ? "light" : "dark"];
  const l = snapshot.level || { level: 1, name: "Initiate", progress: 0 };
  const streak = snapshot.vacationActive ? "\u{1F334}" : String(snapshot.currentStreak || 0);
  const barW = Math.round(360 * Math.min(1, Math.max(0, l.progress || 0)));
  const who = opts.username ? `${opts.username}'s ledger` : "CodeLedger";
  const motion = opts.animate === false ? "" : `
  ${CARD_MOTION}`;
  const cell = (x, value, label, color, cls) => `
    <text class="n ${cls}" x="${x}" y="86" fill="${color}" font-size="34" font-weight="700" text-anchor="middle">${escapeXml(value)}</text>
    <text x="${x}" y="108" fill="${t.muted}" font-size="12" text-anchor="middle">${escapeXml(label)}</text>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="420" height="200" role="img" aria-label="${escapeXml(who)}: ${snapshot.currentStreak || 0} day streak, ${snapshot.totalPoints || 0} points">
  <title>${escapeXml(who)}</title>${motion}
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${t.bg0}"/>
      <stop offset="1" stop-color="${t.bg1}"/>
    </linearGradient>
    <linearGradient id="bar" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="${t.streak}"/>
      <stop offset="1" stop-color="${t.points}"/>
    </linearGradient>
  </defs>
  <rect width="420" height="200" rx="12" fill="url(#bg)"/>
  <rect x="0.5" y="0.5" width="419" height="199" rx="12" fill="none" stroke="${t.border}"/>
  <text x="24" y="36" fill="${t.title}" font-size="15" font-weight="600" font-family="Segoe UI,Helvetica,Arial,sans-serif">${escapeXml(who)}</text>
  <text x="396" y="36" fill="${t.faint}" font-size="12" text-anchor="end" font-family="Segoe UI,Helvetica,Arial,sans-serif">Lv ${escapeXml(l.level)} \xB7 ${escapeXml(l.name)}</text>
  <g font-family="Segoe UI,Helvetica,Arial,sans-serif">
${cell(80, streak, "day streak", t.streak, "n1")}
${cell(210, formatCount(snapshot.totalPoints || 0), "points", t.points, "n2")}
${cell(340, formatCount(snapshot.totalSolves || 0), "solved", t.solved, "n3")}
  </g>
  <rect x="30" y="140" width="360" height="8" rx="4" fill="${t.track}"/>
  <rect class="bar" x="30" y="140" width="${barW}" height="8" rx="4" fill="url(#bar)"/>
  <text x="30" y="172" fill="${t.muted}" font-size="11" font-family="Segoe UI,Helvetica,Arial,sans-serif">${escapeXml(
    l.next ? `${l.into} / ${l.span} to ${l.next.name}` : "Max level"
  )}</text>
  <text x="390" y="172" fill="${t.muted}" font-size="11" text-anchor="end" font-family="Segoe UI,Helvetica,Arial,sans-serif">${escapeXml(
    snapshot.freezes || 0
  )} \u2744 \xB7 best ${escapeXml(snapshot.longestStreak || 0)}d</text>
  <text x="210" y="190" fill="${t.stamp}" font-size="9" text-anchor="middle" font-family="Segoe UI,Helvetica,Arial,sans-serif">${escapeXml(
    asOfLabel(snapshot.today) ? `as of ${asOfLabel(snapshot.today)}` : ""
  )}</text>
</svg>`;
}
var BADGE_DIR = "badges";
function buildBadgeFiles(snapshot, opts = {}) {
  return [
    { path: `${BADGE_DIR}/streak.svg`, content: streakBadge(snapshot) },
    { path: `${BADGE_DIR}/points.svg`, content: pointsBadge(snapshot) },
    { path: `${BADGE_DIR}/level.svg`, content: levelBadge(snapshot) },
    { path: `${BADGE_DIR}/solved.svg`, content: solvedBadge(snapshot) },
    { path: `${BADGE_DIR}/difficulty.svg`, content: difficultyBadge(snapshot) },
    { path: `${BADGE_DIR}/freezes.svg`, content: freezeBadge(snapshot) },
    { path: `${BADGE_DIR}/card.svg`, content: streakCard(snapshot, opts) },
    // `card.svg` stays the dark one so every URL already embedded anywhere keeps
    // meaning what it meant. The light file is the addition, and the README's
    // `<picture>` is what decides between them.
    {
      path: `${BADGE_DIR}/card-light.svg`,
      content: streakCard(snapshot, { ...opts, theme: "light" })
    },
    // A machine-readable copy so the landing page's comparison view and any
    // third-party dashboard can read the same numbers without parsing SVG.
    {
      path: `${BADGE_DIR}/stats.json`,
      content: JSON.stringify(badgeStats(snapshot), null, 2)
    }
  ];
}
function badgeStats(snapshot) {
  return {
    schema: 1,
    // A day, not a timestamp. The scheduled refresh rewrites this file every
    // night; a wall-clock stamp would differ on every run and produce a commit
    // saying nothing changed when nothing did.
    asOf: snapshot.today || "",
    currentStreak: snapshot.currentStreak || 0,
    longestStreak: snapshot.longestStreak || 0,
    freezes: snapshot.freezes || 0,
    totalPoints: snapshot.totalPoints || 0,
    totalSolves: snapshot.totalSolves || 0,
    totalRecalls: snapshot.totalRecalls || 0,
    byDifficulty: snapshot.byDifficulty || {},
    level: snapshot.level?.level || 1,
    levelName: snapshot.level?.name || "Initiate",
    activeDays: snapshot.activeDays || 0,
    dailyTargetPoints: snapshot.dailyTargetPoints || 0,
    achievements: (snapshot.achievements || []).filter((a) => a.earned).map((a) => a.id)
  };
}
function badgeUrl(baseUrl, name, snapshot) {
  const base = String(baseUrl || "").replace(/\/+$/, "");
  return `${base}/${BADGE_DIR}/${name}.svg?v=${encodeURIComponent(cacheKey(snapshot))}`;
}
function cacheKey(snapshot) {
  const s = snapshot || {};
  return [s.totalPoints || 0, s.currentStreak || 0, s.totalSolves || 0, s.today || ""].join("-");
}
var BADGE_ALT = Object.freeze({
  streak: "Streak",
  points: "Points",
  level: "Level",
  solved: "Solved",
  difficulty: "Solved by difficulty",
  freezes: "Freezes"
});
var DEFAULT_PICKS = Object.freeze(["streak", "points", "level", "difficulty", "freezes"]);
function badgeMarkdown(snapshot, opts = {}) {
  const svgUrl = (n) => badgeUrl(opts.pagesUrl || ".", n, snapshot);
  const url = typeof opts.urlFor === "function" ? opts.urlFor : svgUrl;
  const lines = [];
  if (opts.showCard !== false) {
    lines.push(
      "<picture>",
      `  <source media="(prefers-color-scheme: light)" srcset="${escapeXml(svgUrl("card-light"))}">`,
      `  <img src="${escapeXml(svgUrl("card"))}" alt="Streak card" width="420">`,
      "</picture>",
      ""
    );
  }
  const picks = (Array.isArray(opts.picks) && opts.picks.length ? opts.picks : DEFAULT_PICKS).filter((n) => BADGE_NAMES.includes(n));
  if (picks.length) {
    lines.push(picks.map((n) => `![${BADGE_ALT[n]}](${url(n)})`).join(" "));
  }
  const showcase = Array.isArray(opts.achievementPicks) ? new Set(opts.achievementPicks) : null;
  const earned = (snapshot.achievements || []).filter(
    (a) => a.earned && (!showcase || showcase.has(a.id))
  );
  if (earned.length) {
    lines.push("", earned.map((a) => `${a.emoji} ${a.name}`).join(" \xB7 "));
  }
  return lines.join("\n");
}
var README_START = "<!-- codeledger:gamification:start -->";
var README_END = "<!-- codeledger:gamification:end -->";
function upsertReadmeBlock(readme, snapshot, opts = {}) {
  const block = `${README_START}
${badgeMarkdown(snapshot, opts)}
${README_END}`;
  const text = String(readme || "");
  const start = text.indexOf(README_START);
  const end = text.indexOf(README_END);
  if (start !== -1 && end !== -1 && end > start) {
    return text.slice(0, start) + block + text.slice(end + README_END.length);
  }
  if (!text.trim()) return `${block}
`;
  const nl = text.indexOf("\n");
  if (text.startsWith("# ") && nl !== -1) {
    return `${text.slice(0, nl + 1)}
${block}
${text.slice(nl + 1)}`;
  }
  return `${block}

${text}`;
}

// src/core/badge-shields.js
var SHIELDS_DIR = "badges/shields";
var SHIELDS_PATHS = Object.freeze(BADGE_NAMES.map((n) => `${SHIELDS_DIR}/${n}.json`));
var SHIELDS_STYLES = Object.freeze([
  "flat",
  "flat-square",
  "plastic",
  "for-the-badge",
  "social"
]);
function endpointBody(spec) {
  return {
    schemaVersion: 1,
    label: String(spec?.label ?? ""),
    message: String(spec?.value ?? ""),
    // Shields takes hex without the hash. Passing "#f97316" renders grey.
    color: String(spec?.color ?? "").replace(/^#/, ""),
    cacheSeconds: 300
  };
}
function buildShieldsFiles(snapshot) {
  const specs = badgeSpecs(snapshot);
  return BADGE_NAMES.map((name) => ({
    path: `${SHIELDS_DIR}/${name}.json`,
    content: JSON.stringify(endpointBody(specs[name]), null, 2)
  }));
}
function shieldsUrl(rawBase, name, snapshot, opts = {}) {
  const inner = `${String(rawBase).replace(/\/+$/, "")}/${SHIELDS_DIR}/${name}.json?v=${encodeURIComponent(cacheKey(snapshot))}`;
  let url = `https://img.shields.io/endpoint?url=${encodeURIComponent(inner)}`;
  if (SHIELDS_STYLES.includes(opts.style)) url += `&style=${opts.style}`;
  return url;
}

// dev/refresh-badges-entry.js
function readJson(path, fallback) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return fallback;
  }
}
function write(path, content) {
  const dir = dirname(path);
  if (dir && dir !== "." && !existsSync(dir)) mkdirSync(dir, { recursive: true });
  const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (existing === content) return false;
  writeFileSync(path, content, "utf8");
  return true;
}
function main() {
  const index = readJson("index.json", null);
  if (!index || !Array.isArray(index.problems)) {
    console.error("index.json missing or has no problems array \u2014 nothing to refresh");
    process.exit(0);
  }
  const cfg = readJson("badges/config.json", {});
  const config = { ...DEFAULT_CONFIG, ...cfg.config || {} };
  const vacations = Array.isArray(cfg.vacations) ? cfg.vacations : [];
  const snapshot = computeSnapshot(index.problems, {
    config,
    vacations,
    streakFloorDay: cfg.installDay || void 0
  });
  if (snapshot.totalSolves === 0 && index.problems.length > 0) {
    console.error(
      `computed 0 solves from ${index.problems.length} indexed problem(s) \u2014 refusing to overwrite badges with zeros`
    );
    process.exit(0);
  }
  let changed = 0;
  const files = [
    ...buildBadgeFiles(snapshot, { username: cfg.username }),
    ...buildShieldsFiles(snapshot)
  ];
  for (const file of files) {
    if (write(file.path, file.content)) changed++;
  }
  if (cfg.readme !== false && existsSync("README.md")) {
    const readme = readFileSync("README.md", "utf8");
    const useShields = cfg.badgeStyle === "shields" && cfg.rawBase;
    const next = upsertReadmeBlock(readme, snapshot, {
      pagesUrl: cfg.pagesUrl,
      username: cfg.username,
      picks: Array.isArray(cfg.picks) ? cfg.picks : void 0,
      achievementPicks: Array.isArray(cfg.achievementPicks) ? cfg.achievementPicks : void 0,
      urlFor: useShields ? (name) => shieldsUrl(cfg.rawBase, name, snapshot, { style: cfg.shieldsStyle }) : void 0
    });
    if (write("README.md", next)) changed++;
  }
  console.log(
    changed ? `refreshed ${changed} file(s) \u2014 streak ${snapshot.currentStreak}d, ${snapshot.totalPoints} pts` : "already up to date"
  );
}
main();
